version: 2.1
jobs:
   create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file infra.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
   configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
                fingerprints: ["ca:c5:ff:cf:cf:2c:9d:53:74:ee:8d:40:fb:33:30:91"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
              ansible-playbook -i host mplay.yml
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i host mplay.yml
              
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
           requires: 
            - create_infrastructure