version: 2.1
jobs:
   create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file infra.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
   configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
                fingerprints: ["41:69:ca:b7:c2:69:4d:3b:d2:aa:18:f1:aa:aa:7d:48"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
              ansible-playbook -i host mplay.yml
        - run:
            name: Run Playbook and Configure server
            command: |
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          -requires: create_infrastructure