---
- name: "update yum packages."
  become: true
  apt:
    update_cache: true

- name: "upgrade packages"
  become: true
  apt:
    name: "*"
    state: latest

- name: "install node dependencies"
  become: true
  apt:
    name:
      - nodejs
      #- npm # TODO: additional steps required before installing this
    state: present
    update_cache: true

- name: "install pm2"
  become: true
  # npm:
  #   name: "pm2"
  #   global: true
  #   production: true
  #   state: latest
  command: |
    npm install pm2 -g

- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'

- name: "copy files"
  copy:
    src: index.js
    dest: ~/web
    backup: true

- name: "start server"
  shell: pm2 start ~/web/index.js -f